### PR TITLE
Game screen implemented

### PR DESCRIPTION
**Pull request by ebarabanovska**
Game screen implemented and existing code refactored.

### CODE REVIEW

**Comment by dragica** [comment]
+1

**Comment by dnoveska** [comment]
+1

**Comment by sumarsky** [comment]
Before someone merge this, I would like to have an argument.

**Comment by sumarsky** [comment]
In my opinion it would have been better if some variation of MVC pattern was used.
I would like this scene to be as easily and as much reusable as it can be.
Since we will need to load the same scene for several iterations or until the game is finished manually, I prefer having Model (some JavaScript object) that can be loaded to the Controller (Phaser object) to render the View.
Currently the script has four properties of type Models.Option. I suggest we wrap them in another object that will be the Model. At later date the Model will be loaded from the service.

**Pull request closed without merging**
