### PR TITLE
images resize + start screen

### PR DESCRIPTION
**Pull request by sumarsky**
images resize + start screen

### CODE REVIEW

**Comment by taurusmk** [comment]
+1

**Comment by despotovska** [comment]
The images canvas size should be modified so that all of them have the same size 256x265. But the original image ratio should be kept.

**Comment by sumarsky** [comment]
@despotovska sorry for the inconvenience, it is done now :)

**Comment by despotovska** [comment]
+1+1

**Comment by ebarabanovska** [comment]
+1

**Pull request merged**
