### PR TITLE
added monkey animation, minor changes

### PR DESCRIPTION
**Pull request by eljesaz**
- 	Added monkey animation
-    	minor changes according to ts lint definitions

### CODE REVIEW

**Comment by taurusmk** [comment]
Preload, Start and MainGame are just reformatted with alt+shift+F, right?

**Comment by eljesaz** [comment]
@taurusmk vars are also changed to lets  and double braces are shifted to single braces also, and yes some lines were more than 160 chars long and formated with ctrl+shift+F :)

**Comment by eljesaz** [comment]
oh and a acouple of "==" are changed tp "===" @taurusmk

**Comment by taurusmk** [comment]
+1

**Comment by ebarabanovska** [comment]
+1

**Comment by dnoveska** [comment]
+1

**Pull request merged**
