### PR TITLE
Implemented final animation graphics

### PR DESCRIPTION
**Pull request by ebarabanovska**
-  Added image and json file for the final animation			
-  Added model and an array for the final animation.			
-  Implemented Game finished graphics

### CODE REVIEW

**Comment by sumarsky** [comment]
From the **finalAnimationAndSound(): void** 

Why do we have this:
for (let i: number = 0; i < lastAnimation.length; i++) {

and what does this mean:
 if (i !== lastAnimation.length - 1) {

**Comment by ebarabanovska** [comment]
In the **finalAnimationAndSound(): void** function

the **lastAnimation array** consists of 9 sprites added in "final-animation.json" file and the final animation is created within loop from this 9 spites. That's why we have "for (let i: number = 0; i < lastAnimation.length; i++)" loop.

Only on the last 9-th "sprite" animation I am adding happy sound and on **onComplete** event I am invoking "the scene blur effect" and game ends. So if current sprite is not our last sprite, we don't add sound and don't attach **onComplete** event on this sprite, otherwise the game will ends right after the first sprite from the finalAnimation is shown. That's why I added this condition "if (i !== lastAnimation.length - 1)".

**Comment by sumarsky** [comment]
I would have declared a variable with the condition logic.
`var isAnimationFinished = (i !== lastAnimation.length - 1)`
otherwise +1

**Comment by despotovska** [comment]
+1

**Comment by dragica** [comment]
+1

**Pull request merged**
