### PR TITLE
Integration of added animations in the game

### PR DESCRIPTION
**Pull request by ebarabanovska**
Please ignore the commit  "Added bunny animation", it is obsoleted.

- Integration of added animation in the game.

### CODE REVIEW

**Comment by despotovska** [comment]
The createNewAnimationModel method can be deleted from MainGame

**Comment by despotovska** [comment]
It should be only:
playHappyAnimationAndSound(): void {
let model: Models.AnimationModel = this.getNextRandomAnimation();
...
}

**Comment by despotovska** [comment]
+1

**Comment by dragica** [comment]
+1

**Pull request merged**
