### PR TITLE
Singleton gamestate added, game finish basic check, code refactored.

### PR DESCRIPTION
**Pull request by taurusmk**

### CODE REVIEW

**Comment by ebarabanovska** [comment]
The RandomizeGameModelService should be covered with tests (according to the "Definition of Done") and Travis notifies that there are conflicts that must be resolved. @taurusmk Did you get latest version of the code before you made a pull request? Could you please get last version of the code, merge the conflicts on your local machine and after that push the changes again.

**Comment by taurusmk** [comment]
Test for RandomizeGameModelService added.
Latest version was taken but in the meantime new merge was done.

**Comment by eljesaz** [comment]
+1

**Comment by dragica** [comment]
+1

**Comment by eljesaz** [comment]
+1

**Comment by despotovska** [comment]
+1

**Pull request merged**
