### PR TITLE
ENDOTW-128 Game screen - number for wrong options clicked 

### PR DESCRIPTION
**Pull request by despotovska**

### CODE REVIEW

**Comment by sumarsky** [comment]
public balloons: Phaser.TileSprite;
is never used

**Comment by despotovska** [comment]
@sumarsky I didn't noticed the unnecessary properties. I removed them now.

**Comment by sumarsky** [comment]
+1

**Comment by ebarabanovska** [comment]
+1

**Comment by dragica** [comment]
+1

**Pull request merged**
